export const ADD_TO_CART = "ADD_TO_CART";

export const UPDATE_FAVOURITE_STOCK = "UPDATE_FAVOURITE_STOCK";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const EMPTY_CART = "EMPTY_CARD";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";