export const ALL_SUBCATEGORY_REQUEST = "ALL_SUBCATEGORY_REQUEST";
export const ALL_SUBCATEGORY_SUCCESS = "ALL_SUBCATEGORY_SUCCESS";
export const ALL_SUBCATEGORY_FAIL = "ALL_SUBCATEGORY_FAIL";

export const NEW_SUBCATEGORY_REQUEST = "NEW_SUBCATEGORY_REQUEST";
export const NEW_SUBCATEGORY_SUCCESS = "NEW_SUBCATEGORY_SUCCESS";
export const NEW_SUBCATEGORY_RESET = "NEW_SUBCATEGORY_RESET";
export const NEW_SUBCATEGORY_FAIL =  "NEW_SUBCATEGORY_FAIL";

export const UPDATE_SUBCATEGORY_REQUEST = "UPDATE_SUBCATEGORY_REQUEST";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_SUBCATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_RESET = "UPDATE_SUBCATEGORY_RESET";
export const UPDATE_SUBCATEGORY_FAIL = "UPDATE_SUBCATEGORY_FAIL";

export const STOP_BUSINESS_SUBCATEGORY_REQUEST = "STOP_BUSINESS_SUBCATEGORY_REQUEST";
export const STOP_BUSINESS_SUBCATEGORY_SUCCESS = "STOP_BUSINESS_SUBCATEGORY_SUCCESS";
export const STOP_BUSINESS_SUBCATEGORY_RESET = "STOP_BUSINESS_SUBCATEGORY_RESET";
export const STOP_BUSINESS_SUBCATEGORY_FAIL = "STOP_BUSINESS_SUBCATEGORY_FAIL";

export const SUBCATEGORY_DETAILS_REQUEST = "SUBCATEGORY_DETAILS_REQUEST";
export const SUBCATEGORY_DETAILS_SUCCESS = "SUBCATEGORY_DETAILS_SUCCESS";
export const SUBCATEGORY_DETAILS_FAIL = "SUBCATEGORY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
